version: "3"
services:
  backend:
    container_name: backend
    image: node:18.16-alpine3.17
    restart: unless-stopped
    tty: true
    ports:
      - "${BACK_PORT}:5000"
    working_dir: /backend
    volumes:
      - ./backend:/backend
      - ./backend/.env:/backend/.env
    environment:
      - NODE_ENV=dev
      - PORT=${BACK_PORT}
    user: "1000:1000"
  frontend:
    container_name: frontend
    image: node:18.16-alpine3.17
    restart: unless-stopped
    tty: true
    ports:
      - "${FRONT_PORT}:3000"
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=dev
      - PORT=${FRONT_PORT}
    user: "1000:1000"
